sudo: required
services:
  - docker
  
before_install:
  - docker build -t ydockerr/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true ydockerr/docker-react npm run test

after_success:
  - docker build -t ydockerr/docker-react .
  
  # log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ydockerr/docker-react
